#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2019, FeldHost™ (feldhost.net)                                   #
# Copyright 2021, WEDOS Internet a.s. (wedos.com)                            #
#                                                                            #
# Portions copyright 2014-2016, Laurent Grawet <dev@grawet.be>               #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
# -------------------------------------------------------------------------- #

# PREMIGRATE SOURCE DST remote_system_dir vmid dsid template
#  - SOURCE is the host where the VM is running
#  - DST is the host where the VM is to be migrated
#  - remote_system_dir is the path for the VM home in the system datastore
#  - vmid is the id of the VM
#  - dsid is the target datastore
#  - template is the template of the VM in XML and base64 encoded

SRC_HOST=$1
DST_HOST=$2

DST_PATH=$3

VMID=$4
DSID=$5

TEMPLATE_64=$(cat)

#--------------------------------------------------------------------------------

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
fi

source $TMCOMMON

DRIVER_PATH=$(dirname $0)

source ${DRIVER_PATH}/../../etc/datastore/3par/3par.conf
. ${DRIVER_PATH}/../../datastore/3par/scripts_3par.sh

#--------------------------------------------------------------------------------

if [ "$SRC_HOST" == "$DST_HOST" ]; then
    log "Not moving $SRC_HOST to $DST_HOST, they are the same host"
    exit 0
fi

#--------------------------------------------------------------------------------

if [ -n "$7" ]; then
    log "Called from tm/$7 but I've nothing to do"
    exit 0
fi

#-------------------------------------------------------------------------------
# Unmap luns from host
#-------------------------------------------------------------------------------

DISK_IDS=$(onevm show $VMID -x | ${DRIVER_PATH}/../../datastore/xpath.rb --stdin '%m%/VM/TEMPLATE/DISK/DISK_ID')

for k in $DISK_IDS; do
    XPATH="${DRIVER_PATH}/../../datastore/xpath.rb -b $TEMPLATE_64"

    unset i j XPATH_ELEMENTS

    while IFS= read -r -d '' element; do
        XPATH_ELEMENTS[i++]="$element"
    done < <($XPATH     /VM/TEMPLATE/DISK[DISK_ID=$k]/SOURCE \
                        /VM/TEMPLATE/DISK[DISK_ID=$k]/TM_MAD \
                        /VM/TEMPLATE/DISK[DISK_ID=$k]/CLONE \
                        /VM/TEMPLATE/DISK[DISK_ID=$k]/READONLY \
                        /VM/TEMPLATE/DISK[DISK_ID=$k]/IMAGE_ID \
                        /VM/TEMPLATE/DISK[DISK_ID=$k]/DISK_ID \
                        /VM/HISTORY_RECORDS/HISTORY[last\(\)]/DS_ID)

    NAME_WWN=${XPATH_ELEMENTS[j++]}
    TM_MAD=${XPATH_ELEMENTS[j++]}
    CLONE=${XPATH_ELEMENTS[j++]}
    READONLY=${XPATH_ELEMENTS[j++]}
    IMAGE_ID=${XPATH_ELEMENTS[j++]}
    DISK_ID=${XPATH_ELEMENTS[j++]}
    SYS_DSID=${XPATH_ELEMENTS[j++]}

    # Readonly and not clone, so this disk can be used by more VMs at the same time
    if [ "$CLONE" == "NO" ] && [ "$READONLY" == "YES" ]; then
        # check if disk is in use by other VMs
        XPATH="${DRIVER_PATH}/../../datastore/xpath.rb --stdin"
        unset i j XPATH_ELEMENTS

        while IFS= read -r -d '' element; do
            XPATH_ELEMENTS[i++]="$element"
        done < <(oneimage show -x $IMAGE_ID| $XPATH /IMAGE/RUNNING_VMS)

        RUNNING_VMS="${XPATH_ELEMENTS[j++]}"

        # image is used, so exit
        [ "$RUNNING_VMS" != "1" ] && exit 0
    fi

    if [ "$TM_MAD" = "3par" ]; then
        if [ "$CLONE" == "YES" ]; then
            #-------------------------------------------------------------------------------
            # Get system ds information
            #-------------------------------------------------------------------------------

            XPATH="${DRIVER_PATH}/../../datastore/xpath.rb --stdin"
            unset i j XPATH_ELEMENTS

            while IFS= read -r -d '' element; do
                XPATH_ELEMENTS[i++]="$element"
            done < <(onedatastore show -x $SYS_DSID | $XPATH \
                               /DATASTORE/TEMPLATE/API_ENDPOINT \
                               /DATASTORE/TEMPLATE/IP \
                               /DATASTORE/TEMPLATE/PORTALS \
                               /DATASTORE/TEMPLATE/NAMING_TYPE)

            API_ENDPOINT="${XPATH_ELEMENTS[j++]:-$API_ENDPOINT}"
            IP="${XPATH_ELEMENTS[j++]:-$IP}"
            PORTALS="${XPATH_ELEMENTS[j++]:-$PORTALS}"
            NAMING_TYPE="${XPATH_ELEMENTS[j++]:-$NAMING_TYPE}"

            if [ -z "$PORTALS" ]; then
                PORTALS=$(${DRIVER_PATH}/../../datastore/3par/3par.py getIscsiPortals -a $API_ENDPOINT -i $IP -s $SECURE -u $USERNAME \
                                                                            -p $PASSWORD --sort NO)
                if [ $? -ne 0 ]; then
                    error_message "$PORTALS"
                    exit 1
                fi
            fi


            # get VM disk WWN
            NAME_WWN=$(${DRIVER_PATH}/../../datastore/3par/3par.py getVmClone -a $API_ENDPOINT -i $IP -s $SECURE -u $USERNAME \
                                                                        -p $PASSWORD -nt $NAMING_TYPE -vi $VMID -id $DISK_ID)

            if [ $? -ne 0 ]; then
                # -------- Fallback to linstor_un driver ------------
                echo "$TEMPLATE_64" | ${DRIVER_PATH}/../linstor_un/$(basename $0) "$@"
                exit $?
            fi

        else

            ${DRIVER_PATH}/../../datastore/3par/3par.py getVV -a $API_ENDPOINT -i $IP -s $SECURE -u $USERNAME \
                                                                                -p $PASSWORD -n $NAME >/dev/null
            if [ "$?" -ne 0 ]; then
                # -------- Fallback to linstor_un driver ------------
                echo "$TEMPLATE_64" | ${DRIVER_PATH}/../linstor_un/$(basename $0) "$@"
                exit $?
            fi
        fi

        NAME=$(get_vv_name "$NAME_WWN")
        WWN=$(get_vv_wwn "$NAME_WWN")

        FLUSH_CMD=$(cat <<EOF
              set -e
              $(remove_lun "$WWN")
EOF
)

        log "Unmapping $NAME_WWN from $SRC_HOST"

        ssh_exec_and_log "$SRC_HOST" "$FLUSH_CMD" \
            "Error flushing out mapping"

        ${DRIVER_PATH}/../../datastore/3par/3par.py unexportVV -a $API_ENDPOINT -i $IP -s $SECURE -u $USERNAME \
                                                                                 -p $PASSWORD -n $NAME -hs $SRC_HOST

        if [ $? -ne 0 ]; then
          error_message "Error unexporting VV"
          exit 1
        fi

        ${DRIVER_PATH}/../../datastore/3par/3par.py deleteHost -a $API_ENDPOINT -i $IP -s $SECURE -u $USERNAME -p $PASSWORD \
            -hs $SRC_HOST >/dev/null
    
        if [ $? -eq 0 ]; then
            ssh_exec_and_log "$SRC_HOST" "$(iscsi_logout "$PORTALS")"
        fi
    fi
done

migrate_other "$@"

exec_and_log "$SSH $SRC_HOST rm -rf $DST_PATH"

exit 0
